### ISSUE TITLE
mv cli source for naming sake

### ISSUE THREAD

**Issue by vbatts** [TomasTomecek/tmux-top#8]
Rather than:

``` bash
go get github.com/TomasTomecek/tmux-top/cli
mv ${GOPATH}/bin/{cli,tmux-top}
```

The more idiomatic approach would be to have the source in a `./cmd/` sub-directory, so users need only to do:

``` bash
go get github.com/TomasTomecek/tmux-top/cmd/tmux-top
```

**Comment by TomasTomecek** [comment]
Haven't looked into this project for some time and, of course, forgot all the golang. Will rewrite once I get back to this. Thanks Vincent!

**Comment by TomasTomecek** [comment]
17 months sounds like a good time to fix this finally, thanks Vincent!
